"""
Helpers for comparing against paper-provided simulator-side results.

This module loads the numeric tables extracted from Vidur paper figure PDFs under:

- `context/summaries/vidur-kb/paper-results/`

Those tables are generated by:

- `scripts/extract_vidur_paper_results.py`

and are intended to be used as a "paper simulator reference" for sanity-check
reproductions (paper-provided profiling bundle).
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any

from omegaconf import DictConfig
from omegaconf import OmegaConf


@dataclass(frozen=True)
class PaperReferenceRow:
    """One extracted reference value (paper figure numeric table)."""

    metric: str
    percentile: str
    value: float
    model: str
    trace: str
    series: str
    source_json: Path
    source_pdf: str | None


def _load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        payload = json.load(f)
    if not isinstance(payload, dict):
        raise ValueError(f"{path}: expected a JSON object")
    return payload


def _extract_one_row(
    *,
    table: dict[str, Any],
    source_json: Path,
    metric: str,
    model: str,
    trace: str,
    series: str,
) -> PaperReferenceRow:
    percentile = table.get("percentile")
    if not isinstance(percentile, str):
        raise ValueError(f"{source_json}: missing or invalid top-level `percentile`")

    table_metric = table.get("metric")
    if table_metric is not None and str(table_metric) != metric:
        raise ValueError(f"{source_json}: expected metric={metric} but found metric={table_metric}")

    rows = table.get("rows")
    if not isinstance(rows, list):
        raise ValueError(f"{source_json}: missing or invalid top-level `rows`")

    matches = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        if row.get("metric") != metric:
            continue
        if row.get("model") != model:
            continue
        if row.get("trace") != trace:
            continue
        if row.get("series") != series:
            continue
        matches.append(row)

    if not matches:
        raise ValueError(
            f"{source_json}: no matching row for metric={metric}, model={model}, trace={trace}, series={series}"
        )
    if len(matches) > 1:
        raise ValueError(
            f"{source_json}: expected 1 matching row for metric={metric}, model={model}, trace={trace}, series={series} "
            f"but found {len(matches)}"
        )

    value_raw = matches[0].get("value")
    if value_raw is None:
        raise ValueError(f"{source_json}: matching row missing `value`")

    try:
        value = float(value_raw)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{source_json}: matching row `value` is not a float: {value_raw}") from exc

    source_pdf = table.get("source_pdf")
    if source_pdf is not None:
        source_pdf = str(source_pdf)

    return PaperReferenceRow(
        metric=metric,
        percentile=percentile,
        value=value,
        model=model,
        trace=trace,
        series=series,
        source_json=source_json,
        source_pdf=source_pdf,
    )


def load_paper_reference_rows(
    *, metric: str, model: str, trace: str, series: str, percentile_jsons: dict[str, Path]
) -> list[PaperReferenceRow]:
    """
    Load a small set of paper-reference rows for one metric.

    Parameters
    ----------
    metric : str
        Metric column name (paper-fidelity vocabulary).
    model : str
        Paper figure model label (e.g., "LLaMA2-7B (TP1)").
    trace : str
        Paper figure trace label (e.g., "Arxiv-4K").
    series : str
        Paper figure series label (e.g., "predicted" for the simulator bars).
    percentile_jsons : dict[str, Path]
        Mapping from an arbitrary label to a JSON path (typically p50/p95 tables).

    Returns
    -------
    list[PaperReferenceRow]
        Extracted rows.
    """

    rows: list[PaperReferenceRow] = []
    for _, path in percentile_jsons.items():
        table = _load_json(path)
        rows.append(
            _extract_one_row(
                table=table,
                source_json=path,
                metric=metric,
                model=model,
                trace=trace,
                series=series,
            )
        )
    rows.sort(key=lambda r: r.percentile)
    return rows


def maybe_load_paper_reference_rows_from_cfg(cfg: DictConfig, *, repo_root: Path) -> list[PaperReferenceRow] | None:
    """
    Optionally load paper-reference rows from `scenario.paper_reference` config.

    Returns `None` if the config is missing or disabled.
    """

    paper_ref_cfg = OmegaConf.select(cfg, "scenario.paper_reference")
    if paper_ref_cfg is None:
        return None

    enabled = bool(OmegaConf.select(cfg, "scenario.paper_reference.enabled"))
    if not enabled:
        return None

    workload_mode = OmegaConf.select(cfg, "workload.mode")
    if workload_mode not in {"static", "dynamic"}:
        return None

    metric = OmegaConf.select(cfg, f"scenario.paper_reference.{workload_mode}.metric")
    if not metric:
        raise ValueError(f"scenario.paper_reference.{workload_mode}.metric is required when enabled=true")

    model = OmegaConf.select(cfg, "scenario.paper_reference.model")
    trace = OmegaConf.select(cfg, "scenario.paper_reference.trace")
    series = OmegaConf.select(cfg, "scenario.paper_reference.series") or "predicted"
    if not model or not trace:
        raise ValueError("scenario.paper_reference.{model,trace} are required when enabled=true")

    p50_json = OmegaConf.select(cfg, f"scenario.paper_reference.{workload_mode}.p50_json")
    p95_json = OmegaConf.select(cfg, f"scenario.paper_reference.{workload_mode}.p95_json")
    if not p50_json or not p95_json:
        raise ValueError(
            f"scenario.paper_reference.{workload_mode}.p50_json and p95_json are required when enabled=true"
        )

    paths = {"p50": Path(str(p50_json)).expanduser(), "p95": Path(str(p95_json)).expanduser()}
    percentile_jsons: dict[str, Path] = {}
    for label, raw in paths.items():
        resolved = raw if raw.is_absolute() else (repo_root / raw)
        resolved = resolved.resolve()
        if not resolved.exists():
            raise FileNotFoundError(
                f"Paper reference JSON not found: {resolved} "
                f"(hint: run `pixi run python scripts/extract_vidur_paper_results.py`)"
            )
        percentile_jsons[label] = resolved

    return load_paper_reference_rows(
        metric=str(metric),
        model=str(model),
        trace=str(trace),
        series=str(series),
        percentile_jsons=percentile_jsons,
    )

